name: CI-Moseiik

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      # Step 1 : Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3 : Install QEMU
      - name: Install QEMU (for cross-platform emulation)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Step 4 : Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Path where the Docker cache is stored
          key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ hashFiles('**/Dockerfile') }}  # Key for the cache
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}-  # Fallback key to restore cache if no exact match

      # Step 5 : Build Docker image
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            -t moseiik-test:latest \
            -f docker/Dockerfile --load \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max .

      # Step 6 : Run tests
      - name: Run tests
        run: |
          docker run \
            --platform ${{ matrix.platform }} \
            moseiik-test:latest
